# coding: utf-8

"""
DM.API Account

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from dm_api_account.api.account_api import AccountApi


class TestAccountApi(unittest.IsolatedAsyncioTestCase):
    """AccountApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = AccountApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_activate(self) -> None:
        """Test case for activate

        Activate registered user
        """
        pass

    async def test_change_email(self) -> None:
        """Test case for change_email

        Change registered user email
        """
        pass

    async def test_change_password(self) -> None:
        """Test case for change_password

        Change registered user password
        """
        pass

    async def test_get_current(self) -> None:
        """Test case for get_current

        Get current user
        """
        pass

    async def test_register(self) -> None:
        """Test case for register

        Register new user
        """
        pass

    async def test_reset_password(self) -> None:
        """Test case for reset_password

        Reset registered user password
        """
        pass


if __name__ == "__main__":
    unittest.main()
