# coding: utf-8

"""
DM.API Account

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from dm_api_account.models.user_details import UserDetails


class TestUserDetails(unittest.TestCase):
    """UserDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserDetails:
        """Test UserDetails
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UserDetails`
        """
        model = UserDetails()
        if include_optional:
            return UserDetails(
                login = '',
                roles = [
                    'Guest'
                    ],
                medium_picture_url = '',
                small_picture_url = '',
                status = '',
                rating = dm_api_account.models.rating.Rating(
                    enabled = True,
                    quality = 56,
                    quantity = 56, ),
                online = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                location = '',
                registration = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                icq = '',
                skype = '',
                original_picture_url = '',
                info = dm_api_account.models.info_bb_text.InfoBbText(
                    value = '',
                    parse_mode = 'Common', ),
                settings = dm_api_account.models.user_settings.UserSettings(
                    color_schema = 'Modern',
                    nanny_greetings_message = '',
                    paging = dm_api_account.models.paging_settings.PagingSettings(
                        posts_per_page = 56,
                        comments_per_page = 56,
                        topics_per_page = 56,
                        messages_per_page = 56,
                        entities_per_page = 56, ), )
            )
        else:
            return UserDetails(
        )
        """

    def testUserDetails(self):
        """Test UserDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
