# coding: utf-8

"""
DM.API Account

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest


class TestColorSchema(unittest.TestCase):
    """ColorSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testColorSchema(self):
        """Test ColorSchema"""
        # inst = ColorSchema()


if __name__ == "__main__":
    unittest.main()
