# coding: utf-8

"""
DM.API Account

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from dm_api_account.api.login_api import LoginApi


class TestLoginApi(unittest.IsolatedAsyncioTestCase):
    """LoginApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = LoginApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_v1_account_login_all_delete(self) -> None:
        """Test case for v1_account_login_all_delete

        Logout from every device
        """
        pass

    async def test_v1_account_login_delete(self) -> None:
        """Test case for v1_account_login_delete

        Logout as current user
        """
        pass

    async def test_v1_account_login_post(self) -> None:
        """Test case for v1_account_login_post

        Authenticate via credentials
        """
        pass


if __name__ == "__main__":
    unittest.main()
