# coding: utf-8

"""
DM.API Account

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from dm_api_account.models.change_email import ChangeEmail


class TestChangeEmail(unittest.TestCase):
    """ChangeEmail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChangeEmail:
        """Test ChangeEmail
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ChangeEmail`
        """
        model = ChangeEmail()
        if include_optional:
            return ChangeEmail(
                login = '',
                password = '',
                email = ''
            )
        else:
            return ChangeEmail(
        )
        """

    def testChangeEmail(self):
        """Test ChangeEmail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
