# coding: utf-8

"""
DM.API Account

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from dm_api_account.models.user_settings import UserSettings


class TestUserSettings(unittest.TestCase):
    """UserSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserSettings:
        """Test UserSettings
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UserSettings`
        """
        model = UserSettings()
        if include_optional:
            return UserSettings(
                color_schema = 'Modern',
                nanny_greetings_message = '',
                paging = dm_api_account.models.paging_settings.PagingSettings(
                    posts_per_page = 56,
                    comments_per_page = 56,
                    topics_per_page = 56,
                    messages_per_page = 56,
                    entities_per_page = 56, )
            )
        else:
            return UserSettings(
        )
        """

    def testUserSettings(self):
        """Test UserSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
