# coding: utf-8

"""
DM.API Account

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from dm_api_account.models.user_envelope import UserEnvelope


class TestUserEnvelope(unittest.TestCase):
    """UserEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserEnvelope:
        """Test UserEnvelope
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UserEnvelope`
        """
        model = UserEnvelope()
        if include_optional:
            return UserEnvelope(
                resource = dm_api_account.models.user.User(
                    login = '',
                    roles = [
                        'Guest'
                        ],
                    medium_picture_url = '',
                    small_picture_url = '',
                    status = '',
                    rating = dm_api_account.models.rating.Rating(
                        enabled = True,
                        quality = 56,
                        quantity = 56, ),
                    online = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                    name = '',
                    location = '',
                    registration = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                metadata = None
            )
        else:
            return UserEnvelope(
        )
        """

    def testUserEnvelope(self):
        """Test UserEnvelope"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
