# coding: utf-8

"""
DM.API Account

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from dm_api_account.models.login_credentials import LoginCredentials


class TestLoginCredentials(unittest.TestCase):
    """LoginCredentials unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LoginCredentials:
        """Test LoginCredentials
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `LoginCredentials`
        """
        model = LoginCredentials()
        if include_optional:
            return LoginCredentials(
                login = '',
                password = '',
                remember_me = True
            )
        else:
            return LoginCredentials(
        )
        """

    def testLoginCredentials(self):
        """Test LoginCredentials"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
