# coding: utf-8

"""
DM.API Account

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from dm_api_account.models.paging_settings import PagingSettings


class TestPagingSettings(unittest.TestCase):
    """PagingSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PagingSettings:
        """Test PagingSettings
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PagingSettings`
        """
        model = PagingSettings()
        if include_optional:
            return PagingSettings(
                posts_per_page = 56,
                comments_per_page = 56,
                topics_per_page = 56,
                messages_per_page = 56,
                entities_per_page = 56
            )
        else:
            return PagingSettings(
        )
        """

    def testPagingSettings(self):
        """Test PagingSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
