stages:
    - testing
    - reports

run_tests:
    stage: testing
    tags:
    - my_docker
    image: python:3.10-slim
    before_script:
        - pip install --upgrade pip
        - pip install -r requirements.txt
    script:
        - pytest --allure=./allure-results tests
    allow_failure: true
    artifacts:
        when: always
        paths:
            - ./allure-results

allure:
    stage: reports
    tags: 
        - my_docker
    image: frankescobar/allure-socker-service
    script: 
        - allure generate -c ./allure-results -o ./allure-report
    artifacts:
        paths:
            - ./allure-results
            - ./allure-reports
        expire_in: 1 day
    rules:
        - when: always

pages:
    stage: reports
    needs: ["allure"]
    script:
        - mkdir public
        - mv ./allure-reports/* public
    artifacts: 
        paths:
            - public
    rules:
        - when: always