service:
  dm_api_account: "http://5.63.153.31:5051"
  mailhog: "http://5.63.153.31:5025"

user:
  login: "vmenshikov"
  password: "123456789"

telegram:
  chat_id: "410965467"
  token: "8480622365:AAHvVLPi6elsWU96iWt_VCaiba4OmOIsoGE"