
on: [ push, pull_request ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |


          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root

      - name: Run tests
        run: |
          export JAVA_HOME=$JAVA_HOME
          poetry run pytest ./tests --alluredir=./allure-results --disable-warnings
        continue-on-error: true

      - name: Run Coverage
        if: ${{ always()}}
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          python -m packages.notifier.bot

          pip install --upgrade pip
          pip install poetry
          poetry install --no-root --with lint,test

      - name: Run MyPy linter
        if: ${{ always() }}
        run: poetry run mypy .

      - name: Run Ruff linter
        if: ${{ always() }}
        run: poetry run ruff check . --fix

      - name: Run Tests with Pytest
        if: ${{ always() }}
        run: poetry run pytest --alluredir=./allure-results tests


          pip install --upgrade pip
          pip install poetry
          poetry install --no-root --with lint,test

      - name: Run MyPy linter
        if: ${{ always() }}
        run: poetry run mypy .

      - name: Run Ruff linter
        if: ${{ always() }}
        run: poetry run ruff check . --fix

      - name: Run Tests with Pytest
        if: ${{ always() }}
        run: poetry run pytest --alluredir=./allure-results tests

      - name: Generate Allure Report
        uses: mikepenz/action-allure-runner@master
        with:
          results_path: './allure-results/'

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report/

      - name: Swagger Coverage Check
        env:
          SWAGGER_URL: http://5.63.153.31:5051/swagger/Account/swagger.json
        run: |
          curl -LJO https://github.com/viclovsky/swagger-coverage/releases/download/1.5.0/swagger-coverage-1.5.0.zip
          unzip swagger-coverage-1.5.0.zip
          ./swagger-coverage-commandline-1.5.0/bin/swagger-coverage-commandline -s $SWAGGER_URL -i swagger-coverage-output

      - name: Upload Swagger Coverage Report
        uses: actions/upload-artifact@v3
        with:


          name: _site
          path: ./_site
          retention-days: 1

  publish-report:

    runs-on: ubuntu-latest

    needs: generate-report

    name: Publish report

    steps:

      - uses: actions/checkout@v4

      - name: Download site report

        uses: actions/download-artifact@v4

      - name: Upload pages artifact

        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages

        id: deployment

        uses: actions/deploy-pages@v4
      - run: echo "https://zelkova19.github.io/dm-api-gitlab/"
        name: swagger-coverage-report
        path: swagger-coverage-report.html

          name: swagger-coverage-report
          path: swagger-coverage-report.html

